<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-T9TC6QDG" failures="1" tests="6" name="com.billhub.qa.testcases.WithholdingTaxPageTest" time="424.347" errors="0" timestamp="2024-03-20T16:18:06 IST" skipped="0">
  <testcase classname="com.billhub.qa.testcases.WithholdingTaxPageTest" name="AddTaxWithValidDataTest" time="60.841"/>
  <testcase classname="com.billhub.qa.testcases.WithholdingTaxPageTest" name="duplicateWithholdingTaxAddTest" time="61.267">
    <failure message="Test Failed!: duplicate credentials has been saved expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test Failed!: duplicate credentials has been saved expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.billhub.qa.testcases.WithholdingTaxPageTest.duplicateWithholdingTaxAddTest(WithholdingTaxPageTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- duplicateWithholdingTaxAddTest -->
  <testcase classname="com.billhub.qa.testcases.WithholdingTaxPageTest" name="SearchWithholdingTaxByRate" time="60.363"/>
  <testcase classname="com.billhub.qa.testcases.WithholdingTaxPageTest" name="withholdingTaxAppearanceTest" time="80.383"/>
  <testcase classname="com.billhub.qa.testcases.WithholdingTaxPageTest" name="AddTaxWithBlankDataTest" time="80.736"/>
  <testcase classname="com.billhub.qa.testcases.WithholdingTaxPageTest" name="AddTaxWithInvalidDataTest" time="80.757"/>
</testsuite> <!-- com.billhub.qa.testcases.WithholdingTaxPageTest -->
